// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElMe: typeof import('element-plus/es')['ElMe']
  const ElMessageElMessage: typeof import('element-plus/es')['ElMessageElMessage']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
}
export {}
